export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_TITLES = 'FETCH_TITLES'
export const FETCH_DESCRIPTIONS = 'FETCH_DESCRIPTIONS'
export const FETCH_PRICES = 'FETCH_PRICES'
export const FETCH_QUANTITIES = 'FETCH_QUANTITIES'
export const FETCH_MOVIE = 'FETCH_MOVIE'
export const CREATE_MOVIE = 'CREATE_MOVIE'
export const EDIT_MOVIE = 'EDIT_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'


 